version: "3.7"


services:
  evolution_augment:
    build:
      context: ./
      dockerfile: Dockerfile.tpu
      network: host
      args:
        USER: $USER
        UID: $DOCKER_UID
        GID: $DOCKER_GID
    image: srihari/evolution_augment:dev
    shm_size: 16gb
    privileged: true
    entrypoint: /bin/bash
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - WANDB_ENTITY=${WANDB_ENTITY}
      - WANDB_PROJECT=${WANDB_PROJECT}
    volumes:
      - ${PWD}/../:/src:rw
      - $DATASETS_CACHE_DIR:/data:rw